#!/usr/bin/env node
/**
 * Build-time (prebuild) generator for the /infra "IaC-on-display" page. Reads a CURATED list of the
 * REAL infra files from the repo root and emits apps/web/data/iac.generated.ts. Regenerated on every
 * build → the surface can never drift from the actual files. The web Docker builder does `COPY . .`,
 * so infra/ + .github/ are present at build time; the standalone runtime doesn't need them.
 *
 * SECURITY (acceptance-critical): the CURATED allow-list is the primary control — only files known to
 * be secret-free are listed. Backstops: (a) each file is scanned with the verify.sh secret regex and
 * the build HARD-FAILS if anything matches; (b) the Cloudflare tunnel UUID is redacted.
 *   node apps/web/scripts/gen-iac.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", ".."); // apps/web/scripts → repo root

// Curated, secret-free files only. Adding a file here MUST be a deliberate, reviewed choice.
const FILES = [
  {
    path: ".github/workflows/web.yml",
    lang: "yaml",
    title: "CI/CD — build & deploy the web app",
    blurb:
      "GitHub Actions builds the Next.js image, pushes it to GHCR, then pins the tag into kustomize with [skip ci]; ArgoCD on the box watches main and syncs. Push to main = deploy.",
  },
  {
    path: "infra/k8s/core/core.yaml",
    lang: "yaml",
    title: "Go core — Deployment, Service & config",
    blurb:
      "The stdlib Go backend: single replica, distroless non-root, read-only rootfs, 12-factor config via ConfigMap. The HMAC secret is referenced by name, never inlined.",
  },
  {
    path: "infra/k8s/core/kustomization.yaml",
    lang: "yaml",
    title: "Kustomize — the image pin CI writes",
    blurb: "CI rewrites the built image tag here; ArgoCD reconciles the cluster to match. This file is the deploy handshake.",
  },
  {
    path: "infra/k8s/caddy/caddy.yaml",
    lang: "yaml",
    title: "Caddy — reverse proxy & metrics",
    blurb:
      "Fronts the cluster inside k3s: routes /api/* to core (SSE-safe, flush-immediate), everything else to web, and exposes its own Prometheus metrics.",
  },
  {
    path: "infra/cloudflared/config.yml",
    lang: "yaml",
    title: "Cloudflare Tunnel — the front door",
    blurb:
      "cloudflared dials out to Cloudflare's edge with zero inbound ports open on the box; gipc.dev ingress lands on the in-cluster Caddy NodePort. The tunnel id is redacted here.",
  },
  {
    path: "infra/terraform/cloudflare/cloudflare.tf",
    lang: "hcl",
    title: "Terraform — the tunnel + DNS, codified (not yet applied)",
    blurb:
      "The migration path off hand-built: the tunnel and its proxied CNAMEs as import-ready resources. Written and validated — deliberately NOT applied; what serves this page today was provisioned by hand, and applying without importing first would risk the live tunnel. The import commands live in the repo README.",
  },
];

// Mirror scripts/verify.sh SECRET_RX (the committed-secret hard-fail). Split the AWS-key literal so THIS
// script doesn't trip verify.sh's own grep.
const SECRET_RX = new RegExp(
  ["BEGIN (RSA |EC |OPENSSH |PGP )?PRIVATE KEY", "aws_secret_access_key", "-----BEGIN", "xox[baprs]-", "ghp_[A-Za-z0-9]{20,}", "AKIA" + "[0-9A-Z]{16}"].join("|"),
);
const UUID_RX = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;

const out = [];
for (const f of FILES) {
  const abs = join(repoRoot, f.path);
  let content;
  try {
    content = readFileSync(abs, "utf8");
  } catch (e) {
    throw new Error(`gen-iac: cannot read curated file ${f.path}: ${e.message}`);
  }
  if (SECRET_RX.test(content)) {
    throw new Error(`gen-iac: SECRET pattern found in ${f.path} — refusing to render it on /infra`);
  }
  content = content.replace(UUID_RX, "‹tunnel-id›"); // redact the tunnel UUID (semi-public → scrubbed)
  out.push({ ...f, content });
}

const body = `// AUTO-GENERATED by apps/web/scripts/gen-iac.mjs (prebuild). DO NOT EDIT.
// Source of truth = the real infra files; regenerated every build → zero drift. Secret-scrubbed.
export type IaCFile = { path: string; lang: string; title: string; blurb: string; content: string };

export const IAC_FILES: IaCFile[] = ${JSON.stringify(out, null, 2)};
`;

const dest = join(here, "..", "data", "iac.generated.ts");
writeFileSync(dest, body);
console.log(`gen-iac: wrote ${out.length} files → data/iac.generated.ts`);
