// GENERATED by scripts/gen-authenticity.mjs — do not edit by hand.
// Deterministic SHA-256 manifest of the site's stable public assets; regenerated by every
// build's prebuild, so the served copy can't drift from its own assets. The committed copy
// is the out-of-band anchor: cross-check the served /authenticity table against this file on
// GitHub, or re-run the generator and diff.

export type AuthAsset = { path: string; sha256: string; bytes: number };

export const AUTH_ASSETS: readonly AuthAsset[] = [
  {
    "path": "/Gabriel_Carvalho_Resume.pdf",
    "sha256": "bad78698836bf109b9424d4a3155e6eb3148339d4b0304c479732cfcb7f37575",
    "bytes": 95479
  },
  {
    "path": "/Gabriel_Carvalho_Resume.pdf.sig",
    "sha256": "10cc1c61a1dcc96122806468bb662483692a5d23ff709c9398c1b6852cece97e",
    "bytes": 64
  },
  {
    "path": "/resume-pubkey.spki",
    "sha256": "c7255cefc7b4af1dd91b4efeac8b46bfac74409745a1f987d70c6a931c089d4b",
    "bytes": 44
  },
  {
    "path": "/og.png",
    "sha256": "1422ec03231835756e91dc96fa474d3d59f726d904fa6ca1bb08b42233936225",
    "bytes": 43866
  },
  {
    "path": "/icon.svg",
    "sha256": "347c3a5411dce85af4780c202e71f61be562958a21e8519723ce4d5e497864cc",
    "bytes": 776
  },
  {
    "path": "/apple-icon.png",
    "sha256": "260ec472dbd3397088b3d132942de9a063e093339d1fbae05de234f59ed718d4",
    "bytes": 17668
  }
];
