apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: gipc
  labels: { app: web }
spec:
  replicas: 1
  selector:
    matchLabels: { app: web }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: web
          image: ghcr.io/gabrielipcarvalho/gipc-web:latest # tag pinned by CI via kustomization
          ports:
            - containerPort: 3000
          env:
            - { name: NODE_ENV, value: production }
            - { name: PORT, value: "3000" }
          readinessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits: { cpu: "1", memory: 384Mi }
