apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gipc
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/gabrielipcarvalho/gipc-web
    newTag: "691b07dfe1e6e378f705c9326d42e3e886c01714"
