apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gipc
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/gabrielipcarvalho/gipc-web
    newTag: "8910ecd93b6f6ea71e9396fbe6d8b4d4dd6c0e34"
