apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gipc
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/gabrielipcarvalho/gipc-web
    newTag: "03575cdc82c36f37cb64f384c362bbeb5482a679"
